#!/usr/bin/env bash

if
  [[ -s "/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/environment" ]]
then
  source "/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/environment"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/environment'" >&2
  exit 1
fi
